/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2016-10-11")
public class PrimitiveThenStruct implements org.apache.thrift.TBase<PrimitiveThenStruct, PrimitiveThenStruct._Fields>, java.io.Serializable, Cloneable, Comparable<PrimitiveThenStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrimitiveThenStruct");

  private static final org.apache.thrift.protocol.TField BLAH_FIELD_DESC = new org.apache.thrift.protocol.TField("blah", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField BLAH2_FIELD_DESC = new org.apache.thrift.protocol.TField("blah2", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField BW_FIELD_DESC = new org.apache.thrift.protocol.TField("bw", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final SchemeFactory STANDARD_SCHEME_FACTORY = new PrimitiveThenStructStandardSchemeFactory();
  private static final SchemeFactory TUPLE_SCHEME_FACTORY = new PrimitiveThenStructTupleSchemeFactory();

  public int blah; // required
  public int blah2; // required
  public Backwards bw; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BLAH((short)1, "blah"),
    BLAH2((short)2, "blah2"),
    BW((short)3, "bw");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BLAH
          return BLAH;
        case 2: // BLAH2
          return BLAH2;
        case 3: // BW
          return BW;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BLAH_ISSET_ID = 0;
  private static final int __BLAH2_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BLAH, new org.apache.thrift.meta_data.FieldMetaData("blah", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BLAH2, new org.apache.thrift.meta_data.FieldMetaData("blah2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BW, new org.apache.thrift.meta_data.FieldMetaData("bw", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Backwards.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrimitiveThenStruct.class, metaDataMap);
  }

  public PrimitiveThenStruct() {
  }

  public PrimitiveThenStruct(
    int blah,
    int blah2,
    Backwards bw)
  {
    this();
    this.blah = blah;
    setBlahIsSet(true);
    this.blah2 = blah2;
    setBlah2IsSet(true);
    this.bw = bw;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrimitiveThenStruct(PrimitiveThenStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.blah = other.blah;
    this.blah2 = other.blah2;
    if (other.isSetBw()) {
      this.bw = new Backwards(other.bw);
    }
  }

  public PrimitiveThenStruct deepCopy() {
    return new PrimitiveThenStruct(this);
  }

  @Override
  public void clear() {
    setBlahIsSet(false);
    this.blah = 0;
    setBlah2IsSet(false);
    this.blah2 = 0;
    this.bw = null;
  }

  public int getBlah() {
    return this.blah;
  }

  public PrimitiveThenStruct setBlah(int blah) {
    this.blah = blah;
    setBlahIsSet(true);
    return this;
  }

  public void unsetBlah() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BLAH_ISSET_ID);
  }

  /** Returns true if field blah is set (has been assigned a value) and false otherwise */
  public boolean isSetBlah() {
    return EncodingUtils.testBit(__isset_bitfield, __BLAH_ISSET_ID);
  }

  public void setBlahIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BLAH_ISSET_ID, value);
  }

  public int getBlah2() {
    return this.blah2;
  }

  public PrimitiveThenStruct setBlah2(int blah2) {
    this.blah2 = blah2;
    setBlah2IsSet(true);
    return this;
  }

  public void unsetBlah2() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BLAH2_ISSET_ID);
  }

  /** Returns true if field blah2 is set (has been assigned a value) and false otherwise */
  public boolean isSetBlah2() {
    return EncodingUtils.testBit(__isset_bitfield, __BLAH2_ISSET_ID);
  }

  public void setBlah2IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BLAH2_ISSET_ID, value);
  }

  public Backwards getBw() {
    return this.bw;
  }

  public PrimitiveThenStruct setBw(Backwards bw) {
    this.bw = bw;
    return this;
  }

  public void unsetBw() {
    this.bw = null;
  }

  /** Returns true if field bw is set (has been assigned a value) and false otherwise */
  public boolean isSetBw() {
    return this.bw != null;
  }

  public void setBwIsSet(boolean value) {
    if (!value) {
      this.bw = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BLAH:
      if (value == null) {
        unsetBlah();
      } else {
        setBlah((Integer)value);
      }
      break;

    case BLAH2:
      if (value == null) {
        unsetBlah2();
      } else {
        setBlah2((Integer)value);
      }
      break;

    case BW:
      if (value == null) {
        unsetBw();
      } else {
        setBw((Backwards)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BLAH:
      return getBlah();

    case BLAH2:
      return getBlah2();

    case BW:
      return getBw();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BLAH:
      return isSetBlah();
    case BLAH2:
      return isSetBlah2();
    case BW:
      return isSetBw();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PrimitiveThenStruct)
      return this.equals((PrimitiveThenStruct)that);
    return false;
  }

  public boolean equals(PrimitiveThenStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_blah = true;
    boolean that_present_blah = true;
    if (this_present_blah || that_present_blah) {
      if (!(this_present_blah && that_present_blah))
        return false;
      if (this.blah != that.blah)
        return false;
    }

    boolean this_present_blah2 = true;
    boolean that_present_blah2 = true;
    if (this_present_blah2 || that_present_blah2) {
      if (!(this_present_blah2 && that_present_blah2))
        return false;
      if (this.blah2 != that.blah2)
        return false;
    }

    boolean this_present_bw = true && this.isSetBw();
    boolean that_present_bw = true && that.isSetBw();
    if (this_present_bw || that_present_bw) {
      if (!(this_present_bw && that_present_bw))
        return false;
      if (!this.bw.equals(that.bw))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + blah;

    hashCode = hashCode * 8191 + blah2;

    hashCode = hashCode * 8191 + ((isSetBw()) ? 131071 : 524287);
    if (isSetBw())
      hashCode = hashCode * 8191 + bw.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PrimitiveThenStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBlah()).compareTo(other.isSetBlah());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlah()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blah, other.blah);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBlah2()).compareTo(other.isSetBlah2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlah2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blah2, other.blah2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBw()).compareTo(other.isSetBw());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBw()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bw, other.bw);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PrimitiveThenStruct(");
    boolean first = true;

    sb.append("blah:");
    sb.append(this.blah);
    first = false;
    if (!first) sb.append(", ");
    sb.append("blah2:");
    sb.append(this.blah2);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bw:");
    if (this.bw == null) {
      sb.append("null");
    } else {
      sb.append(this.bw);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (bw != null) {
      bw.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrimitiveThenStructStandardSchemeFactory implements SchemeFactory {
    public PrimitiveThenStructStandardScheme getScheme() {
      return new PrimitiveThenStructStandardScheme();
    }
  }

  private static class PrimitiveThenStructStandardScheme extends StandardScheme<PrimitiveThenStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PrimitiveThenStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BLAH
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.blah = iprot.readI32();
              struct.setBlahIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BLAH2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.blah2 = iprot.readI32();
              struct.setBlah2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BW
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.bw = new Backwards();
              struct.bw.read(iprot);
              struct.setBwIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PrimitiveThenStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BLAH_FIELD_DESC);
      oprot.writeI32(struct.blah);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BLAH2_FIELD_DESC);
      oprot.writeI32(struct.blah2);
      oprot.writeFieldEnd();
      if (struct.bw != null) {
        oprot.writeFieldBegin(BW_FIELD_DESC);
        struct.bw.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrimitiveThenStructTupleSchemeFactory implements SchemeFactory {
    public PrimitiveThenStructTupleScheme getScheme() {
      return new PrimitiveThenStructTupleScheme();
    }
  }

  private static class PrimitiveThenStructTupleScheme extends TupleScheme<PrimitiveThenStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrimitiveThenStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBlah()) {
        optionals.set(0);
      }
      if (struct.isSetBlah2()) {
        optionals.set(1);
      }
      if (struct.isSetBw()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetBlah()) {
        oprot.writeI32(struct.blah);
      }
      if (struct.isSetBlah2()) {
        oprot.writeI32(struct.blah2);
      }
      if (struct.isSetBw()) {
        struct.bw.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrimitiveThenStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.blah = iprot.readI32();
        struct.setBlahIsSet(true);
      }
      if (incoming.get(1)) {
        struct.blah2 = iprot.readI32();
        struct.setBlah2IsSet(true);
      }
      if (incoming.get(2)) {
        struct.bw = new Backwards();
        struct.bw.read(iprot);
        struct.setBwIsSet(true);
      }
    }
  }

  private static <S extends IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

