/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift.test;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2016-10-11")
public class TupleProtocolTestStruct implements org.apache.thrift.TBase<TupleProtocolTestStruct, TupleProtocolTestStruct._Fields>, java.io.Serializable, Cloneable, Comparable<TupleProtocolTestStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TupleProtocolTestStruct");

  private static final org.apache.thrift.protocol.TField FIELD1_FIELD_DESC = new org.apache.thrift.protocol.TField("field1", org.apache.thrift.protocol.TType.I32, (short)-1);
  private static final org.apache.thrift.protocol.TField FIELD2_FIELD_DESC = new org.apache.thrift.protocol.TField("field2", org.apache.thrift.protocol.TType.I32, (short)-2);
  private static final org.apache.thrift.protocol.TField FIELD3_FIELD_DESC = new org.apache.thrift.protocol.TField("field3", org.apache.thrift.protocol.TType.I32, (short)-3);
  private static final org.apache.thrift.protocol.TField FIELD4_FIELD_DESC = new org.apache.thrift.protocol.TField("field4", org.apache.thrift.protocol.TType.I32, (short)-4);
  private static final org.apache.thrift.protocol.TField FIELD5_FIELD_DESC = new org.apache.thrift.protocol.TField("field5", org.apache.thrift.protocol.TType.I32, (short)-5);
  private static final org.apache.thrift.protocol.TField FIELD6_FIELD_DESC = new org.apache.thrift.protocol.TField("field6", org.apache.thrift.protocol.TType.I32, (short)-6);
  private static final org.apache.thrift.protocol.TField FIELD7_FIELD_DESC = new org.apache.thrift.protocol.TField("field7", org.apache.thrift.protocol.TType.I32, (short)-7);
  private static final org.apache.thrift.protocol.TField FIELD8_FIELD_DESC = new org.apache.thrift.protocol.TField("field8", org.apache.thrift.protocol.TType.I32, (short)-8);
  private static final org.apache.thrift.protocol.TField FIELD9_FIELD_DESC = new org.apache.thrift.protocol.TField("field9", org.apache.thrift.protocol.TType.I32, (short)-9);
  private static final org.apache.thrift.protocol.TField FIELD10_FIELD_DESC = new org.apache.thrift.protocol.TField("field10", org.apache.thrift.protocol.TType.I32, (short)-10);
  private static final org.apache.thrift.protocol.TField FIELD11_FIELD_DESC = new org.apache.thrift.protocol.TField("field11", org.apache.thrift.protocol.TType.I32, (short)-11);
  private static final org.apache.thrift.protocol.TField FIELD12_FIELD_DESC = new org.apache.thrift.protocol.TField("field12", org.apache.thrift.protocol.TType.I32, (short)-12);

  private static final SchemeFactory STANDARD_SCHEME_FACTORY = new TupleProtocolTestStructStandardSchemeFactory();
  private static final SchemeFactory TUPLE_SCHEME_FACTORY = new TupleProtocolTestStructTupleSchemeFactory();

  public int field1; // optional
  public int field2; // optional
  public int field3; // optional
  public int field4; // optional
  public int field5; // optional
  public int field6; // optional
  public int field7; // optional
  public int field8; // optional
  public int field9; // optional
  public int field10; // optional
  public int field11; // optional
  public int field12; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FIELD1((short)-1, "field1"),
    FIELD2((short)-2, "field2"),
    FIELD3((short)-3, "field3"),
    FIELD4((short)-4, "field4"),
    FIELD5((short)-5, "field5"),
    FIELD6((short)-6, "field6"),
    FIELD7((short)-7, "field7"),
    FIELD8((short)-8, "field8"),
    FIELD9((short)-9, "field9"),
    FIELD10((short)-10, "field10"),
    FIELD11((short)-11, "field11"),
    FIELD12((short)-12, "field12");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case -1: // FIELD1
          return FIELD1;
        case -2: // FIELD2
          return FIELD2;
        case -3: // FIELD3
          return FIELD3;
        case -4: // FIELD4
          return FIELD4;
        case -5: // FIELD5
          return FIELD5;
        case -6: // FIELD6
          return FIELD6;
        case -7: // FIELD7
          return FIELD7;
        case -8: // FIELD8
          return FIELD8;
        case -9: // FIELD9
          return FIELD9;
        case -10: // FIELD10
          return FIELD10;
        case -11: // FIELD11
          return FIELD11;
        case -12: // FIELD12
          return FIELD12;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FIELD1_ISSET_ID = 0;
  private static final int __FIELD2_ISSET_ID = 1;
  private static final int __FIELD3_ISSET_ID = 2;
  private static final int __FIELD4_ISSET_ID = 3;
  private static final int __FIELD5_ISSET_ID = 4;
  private static final int __FIELD6_ISSET_ID = 5;
  private static final int __FIELD7_ISSET_ID = 6;
  private static final int __FIELD8_ISSET_ID = 7;
  private static final int __FIELD9_ISSET_ID = 8;
  private static final int __FIELD10_ISSET_ID = 9;
  private static final int __FIELD11_ISSET_ID = 10;
  private static final int __FIELD12_ISSET_ID = 11;
  private short __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.FIELD1,_Fields.FIELD2,_Fields.FIELD3,_Fields.FIELD4,_Fields.FIELD5,_Fields.FIELD6,_Fields.FIELD7,_Fields.FIELD8,_Fields.FIELD9,_Fields.FIELD10,_Fields.FIELD11,_Fields.FIELD12};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FIELD1, new org.apache.thrift.meta_data.FieldMetaData("field1", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD2, new org.apache.thrift.meta_data.FieldMetaData("field2", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD3, new org.apache.thrift.meta_data.FieldMetaData("field3", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD4, new org.apache.thrift.meta_data.FieldMetaData("field4", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD5, new org.apache.thrift.meta_data.FieldMetaData("field5", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD6, new org.apache.thrift.meta_data.FieldMetaData("field6", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD7, new org.apache.thrift.meta_data.FieldMetaData("field7", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD8, new org.apache.thrift.meta_data.FieldMetaData("field8", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD9, new org.apache.thrift.meta_data.FieldMetaData("field9", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD10, new org.apache.thrift.meta_data.FieldMetaData("field10", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD11, new org.apache.thrift.meta_data.FieldMetaData("field11", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FIELD12, new org.apache.thrift.meta_data.FieldMetaData("field12", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TupleProtocolTestStruct.class, metaDataMap);
  }

  public TupleProtocolTestStruct() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TupleProtocolTestStruct(TupleProtocolTestStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    this.field1 = other.field1;
    this.field2 = other.field2;
    this.field3 = other.field3;
    this.field4 = other.field4;
    this.field5 = other.field5;
    this.field6 = other.field6;
    this.field7 = other.field7;
    this.field8 = other.field8;
    this.field9 = other.field9;
    this.field10 = other.field10;
    this.field11 = other.field11;
    this.field12 = other.field12;
  }

  public TupleProtocolTestStruct deepCopy() {
    return new TupleProtocolTestStruct(this);
  }

  @Override
  public void clear() {
    setField1IsSet(false);
    this.field1 = 0;
    setField2IsSet(false);
    this.field2 = 0;
    setField3IsSet(false);
    this.field3 = 0;
    setField4IsSet(false);
    this.field4 = 0;
    setField5IsSet(false);
    this.field5 = 0;
    setField6IsSet(false);
    this.field6 = 0;
    setField7IsSet(false);
    this.field7 = 0;
    setField8IsSet(false);
    this.field8 = 0;
    setField9IsSet(false);
    this.field9 = 0;
    setField10IsSet(false);
    this.field10 = 0;
    setField11IsSet(false);
    this.field11 = 0;
    setField12IsSet(false);
    this.field12 = 0;
  }

  public int getField1() {
    return this.field1;
  }

  public TupleProtocolTestStruct setField1(int field1) {
    this.field1 = field1;
    setField1IsSet(true);
    return this;
  }

  public void unsetField1() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD1_ISSET_ID);
  }

  /** Returns true if field field1 is set (has been assigned a value) and false otherwise */
  public boolean isSetField1() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD1_ISSET_ID);
  }

  public void setField1IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD1_ISSET_ID, value);
  }

  public int getField2() {
    return this.field2;
  }

  public TupleProtocolTestStruct setField2(int field2) {
    this.field2 = field2;
    setField2IsSet(true);
    return this;
  }

  public void unsetField2() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD2_ISSET_ID);
  }

  /** Returns true if field field2 is set (has been assigned a value) and false otherwise */
  public boolean isSetField2() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD2_ISSET_ID);
  }

  public void setField2IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD2_ISSET_ID, value);
  }

  public int getField3() {
    return this.field3;
  }

  public TupleProtocolTestStruct setField3(int field3) {
    this.field3 = field3;
    setField3IsSet(true);
    return this;
  }

  public void unsetField3() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD3_ISSET_ID);
  }

  /** Returns true if field field3 is set (has been assigned a value) and false otherwise */
  public boolean isSetField3() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD3_ISSET_ID);
  }

  public void setField3IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD3_ISSET_ID, value);
  }

  public int getField4() {
    return this.field4;
  }

  public TupleProtocolTestStruct setField4(int field4) {
    this.field4 = field4;
    setField4IsSet(true);
    return this;
  }

  public void unsetField4() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD4_ISSET_ID);
  }

  /** Returns true if field field4 is set (has been assigned a value) and false otherwise */
  public boolean isSetField4() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD4_ISSET_ID);
  }

  public void setField4IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD4_ISSET_ID, value);
  }

  public int getField5() {
    return this.field5;
  }

  public TupleProtocolTestStruct setField5(int field5) {
    this.field5 = field5;
    setField5IsSet(true);
    return this;
  }

  public void unsetField5() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD5_ISSET_ID);
  }

  /** Returns true if field field5 is set (has been assigned a value) and false otherwise */
  public boolean isSetField5() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD5_ISSET_ID);
  }

  public void setField5IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD5_ISSET_ID, value);
  }

  public int getField6() {
    return this.field6;
  }

  public TupleProtocolTestStruct setField6(int field6) {
    this.field6 = field6;
    setField6IsSet(true);
    return this;
  }

  public void unsetField6() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD6_ISSET_ID);
  }

  /** Returns true if field field6 is set (has been assigned a value) and false otherwise */
  public boolean isSetField6() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD6_ISSET_ID);
  }

  public void setField6IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD6_ISSET_ID, value);
  }

  public int getField7() {
    return this.field7;
  }

  public TupleProtocolTestStruct setField7(int field7) {
    this.field7 = field7;
    setField7IsSet(true);
    return this;
  }

  public void unsetField7() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD7_ISSET_ID);
  }

  /** Returns true if field field7 is set (has been assigned a value) and false otherwise */
  public boolean isSetField7() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD7_ISSET_ID);
  }

  public void setField7IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD7_ISSET_ID, value);
  }

  public int getField8() {
    return this.field8;
  }

  public TupleProtocolTestStruct setField8(int field8) {
    this.field8 = field8;
    setField8IsSet(true);
    return this;
  }

  public void unsetField8() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD8_ISSET_ID);
  }

  /** Returns true if field field8 is set (has been assigned a value) and false otherwise */
  public boolean isSetField8() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD8_ISSET_ID);
  }

  public void setField8IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD8_ISSET_ID, value);
  }

  public int getField9() {
    return this.field9;
  }

  public TupleProtocolTestStruct setField9(int field9) {
    this.field9 = field9;
    setField9IsSet(true);
    return this;
  }

  public void unsetField9() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD9_ISSET_ID);
  }

  /** Returns true if field field9 is set (has been assigned a value) and false otherwise */
  public boolean isSetField9() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD9_ISSET_ID);
  }

  public void setField9IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD9_ISSET_ID, value);
  }

  public int getField10() {
    return this.field10;
  }

  public TupleProtocolTestStruct setField10(int field10) {
    this.field10 = field10;
    setField10IsSet(true);
    return this;
  }

  public void unsetField10() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD10_ISSET_ID);
  }

  /** Returns true if field field10 is set (has been assigned a value) and false otherwise */
  public boolean isSetField10() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD10_ISSET_ID);
  }

  public void setField10IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD10_ISSET_ID, value);
  }

  public int getField11() {
    return this.field11;
  }

  public TupleProtocolTestStruct setField11(int field11) {
    this.field11 = field11;
    setField11IsSet(true);
    return this;
  }

  public void unsetField11() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD11_ISSET_ID);
  }

  /** Returns true if field field11 is set (has been assigned a value) and false otherwise */
  public boolean isSetField11() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD11_ISSET_ID);
  }

  public void setField11IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD11_ISSET_ID, value);
  }

  public int getField12() {
    return this.field12;
  }

  public TupleProtocolTestStruct setField12(int field12) {
    this.field12 = field12;
    setField12IsSet(true);
    return this;
  }

  public void unsetField12() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FIELD12_ISSET_ID);
  }

  /** Returns true if field field12 is set (has been assigned a value) and false otherwise */
  public boolean isSetField12() {
    return EncodingUtils.testBit(__isset_bitfield, __FIELD12_ISSET_ID);
  }

  public void setField12IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FIELD12_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FIELD1:
      if (value == null) {
        unsetField1();
      } else {
        setField1((Integer)value);
      }
      break;

    case FIELD2:
      if (value == null) {
        unsetField2();
      } else {
        setField2((Integer)value);
      }
      break;

    case FIELD3:
      if (value == null) {
        unsetField3();
      } else {
        setField3((Integer)value);
      }
      break;

    case FIELD4:
      if (value == null) {
        unsetField4();
      } else {
        setField4((Integer)value);
      }
      break;

    case FIELD5:
      if (value == null) {
        unsetField5();
      } else {
        setField5((Integer)value);
      }
      break;

    case FIELD6:
      if (value == null) {
        unsetField6();
      } else {
        setField6((Integer)value);
      }
      break;

    case FIELD7:
      if (value == null) {
        unsetField7();
      } else {
        setField7((Integer)value);
      }
      break;

    case FIELD8:
      if (value == null) {
        unsetField8();
      } else {
        setField8((Integer)value);
      }
      break;

    case FIELD9:
      if (value == null) {
        unsetField9();
      } else {
        setField9((Integer)value);
      }
      break;

    case FIELD10:
      if (value == null) {
        unsetField10();
      } else {
        setField10((Integer)value);
      }
      break;

    case FIELD11:
      if (value == null) {
        unsetField11();
      } else {
        setField11((Integer)value);
      }
      break;

    case FIELD12:
      if (value == null) {
        unsetField12();
      } else {
        setField12((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FIELD1:
      return getField1();

    case FIELD2:
      return getField2();

    case FIELD3:
      return getField3();

    case FIELD4:
      return getField4();

    case FIELD5:
      return getField5();

    case FIELD6:
      return getField6();

    case FIELD7:
      return getField7();

    case FIELD8:
      return getField8();

    case FIELD9:
      return getField9();

    case FIELD10:
      return getField10();

    case FIELD11:
      return getField11();

    case FIELD12:
      return getField12();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FIELD1:
      return isSetField1();
    case FIELD2:
      return isSetField2();
    case FIELD3:
      return isSetField3();
    case FIELD4:
      return isSetField4();
    case FIELD5:
      return isSetField5();
    case FIELD6:
      return isSetField6();
    case FIELD7:
      return isSetField7();
    case FIELD8:
      return isSetField8();
    case FIELD9:
      return isSetField9();
    case FIELD10:
      return isSetField10();
    case FIELD11:
      return isSetField11();
    case FIELD12:
      return isSetField12();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TupleProtocolTestStruct)
      return this.equals((TupleProtocolTestStruct)that);
    return false;
  }

  public boolean equals(TupleProtocolTestStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_field1 = true && this.isSetField1();
    boolean that_present_field1 = true && that.isSetField1();
    if (this_present_field1 || that_present_field1) {
      if (!(this_present_field1 && that_present_field1))
        return false;
      if (this.field1 != that.field1)
        return false;
    }

    boolean this_present_field2 = true && this.isSetField2();
    boolean that_present_field2 = true && that.isSetField2();
    if (this_present_field2 || that_present_field2) {
      if (!(this_present_field2 && that_present_field2))
        return false;
      if (this.field2 != that.field2)
        return false;
    }

    boolean this_present_field3 = true && this.isSetField3();
    boolean that_present_field3 = true && that.isSetField3();
    if (this_present_field3 || that_present_field3) {
      if (!(this_present_field3 && that_present_field3))
        return false;
      if (this.field3 != that.field3)
        return false;
    }

    boolean this_present_field4 = true && this.isSetField4();
    boolean that_present_field4 = true && that.isSetField4();
    if (this_present_field4 || that_present_field4) {
      if (!(this_present_field4 && that_present_field4))
        return false;
      if (this.field4 != that.field4)
        return false;
    }

    boolean this_present_field5 = true && this.isSetField5();
    boolean that_present_field5 = true && that.isSetField5();
    if (this_present_field5 || that_present_field5) {
      if (!(this_present_field5 && that_present_field5))
        return false;
      if (this.field5 != that.field5)
        return false;
    }

    boolean this_present_field6 = true && this.isSetField6();
    boolean that_present_field6 = true && that.isSetField6();
    if (this_present_field6 || that_present_field6) {
      if (!(this_present_field6 && that_present_field6))
        return false;
      if (this.field6 != that.field6)
        return false;
    }

    boolean this_present_field7 = true && this.isSetField7();
    boolean that_present_field7 = true && that.isSetField7();
    if (this_present_field7 || that_present_field7) {
      if (!(this_present_field7 && that_present_field7))
        return false;
      if (this.field7 != that.field7)
        return false;
    }

    boolean this_present_field8 = true && this.isSetField8();
    boolean that_present_field8 = true && that.isSetField8();
    if (this_present_field8 || that_present_field8) {
      if (!(this_present_field8 && that_present_field8))
        return false;
      if (this.field8 != that.field8)
        return false;
    }

    boolean this_present_field9 = true && this.isSetField9();
    boolean that_present_field9 = true && that.isSetField9();
    if (this_present_field9 || that_present_field9) {
      if (!(this_present_field9 && that_present_field9))
        return false;
      if (this.field9 != that.field9)
        return false;
    }

    boolean this_present_field10 = true && this.isSetField10();
    boolean that_present_field10 = true && that.isSetField10();
    if (this_present_field10 || that_present_field10) {
      if (!(this_present_field10 && that_present_field10))
        return false;
      if (this.field10 != that.field10)
        return false;
    }

    boolean this_present_field11 = true && this.isSetField11();
    boolean that_present_field11 = true && that.isSetField11();
    if (this_present_field11 || that_present_field11) {
      if (!(this_present_field11 && that_present_field11))
        return false;
      if (this.field11 != that.field11)
        return false;
    }

    boolean this_present_field12 = true && this.isSetField12();
    boolean that_present_field12 = true && that.isSetField12();
    if (this_present_field12 || that_present_field12) {
      if (!(this_present_field12 && that_present_field12))
        return false;
      if (this.field12 != that.field12)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetField1()) ? 131071 : 524287);
    if (isSetField1())
      hashCode = hashCode * 8191 + field1;

    hashCode = hashCode * 8191 + ((isSetField2()) ? 131071 : 524287);
    if (isSetField2())
      hashCode = hashCode * 8191 + field2;

    hashCode = hashCode * 8191 + ((isSetField3()) ? 131071 : 524287);
    if (isSetField3())
      hashCode = hashCode * 8191 + field3;

    hashCode = hashCode * 8191 + ((isSetField4()) ? 131071 : 524287);
    if (isSetField4())
      hashCode = hashCode * 8191 + field4;

    hashCode = hashCode * 8191 + ((isSetField5()) ? 131071 : 524287);
    if (isSetField5())
      hashCode = hashCode * 8191 + field5;

    hashCode = hashCode * 8191 + ((isSetField6()) ? 131071 : 524287);
    if (isSetField6())
      hashCode = hashCode * 8191 + field6;

    hashCode = hashCode * 8191 + ((isSetField7()) ? 131071 : 524287);
    if (isSetField7())
      hashCode = hashCode * 8191 + field7;

    hashCode = hashCode * 8191 + ((isSetField8()) ? 131071 : 524287);
    if (isSetField8())
      hashCode = hashCode * 8191 + field8;

    hashCode = hashCode * 8191 + ((isSetField9()) ? 131071 : 524287);
    if (isSetField9())
      hashCode = hashCode * 8191 + field9;

    hashCode = hashCode * 8191 + ((isSetField10()) ? 131071 : 524287);
    if (isSetField10())
      hashCode = hashCode * 8191 + field10;

    hashCode = hashCode * 8191 + ((isSetField11()) ? 131071 : 524287);
    if (isSetField11())
      hashCode = hashCode * 8191 + field11;

    hashCode = hashCode * 8191 + ((isSetField12()) ? 131071 : 524287);
    if (isSetField12())
      hashCode = hashCode * 8191 + field12;

    return hashCode;
  }

  @Override
  public int compareTo(TupleProtocolTestStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetField1()).compareTo(other.isSetField1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field1, other.field1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField2()).compareTo(other.isSetField2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field2, other.field2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField3()).compareTo(other.isSetField3());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField3()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field3, other.field3);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField4()).compareTo(other.isSetField4());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField4()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field4, other.field4);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField5()).compareTo(other.isSetField5());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField5()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field5, other.field5);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField6()).compareTo(other.isSetField6());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField6()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field6, other.field6);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField7()).compareTo(other.isSetField7());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField7()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field7, other.field7);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField8()).compareTo(other.isSetField8());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField8()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field8, other.field8);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField9()).compareTo(other.isSetField9());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField9()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field9, other.field9);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField10()).compareTo(other.isSetField10());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField10()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field10, other.field10);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField11()).compareTo(other.isSetField11());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField11()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field11, other.field11);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetField12()).compareTo(other.isSetField12());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetField12()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.field12, other.field12);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TupleProtocolTestStruct(");
    boolean first = true;

    if (isSetField1()) {
      sb.append("field1:");
      sb.append(this.field1);
      first = false;
    }
    if (isSetField2()) {
      if (!first) sb.append(", ");
      sb.append("field2:");
      sb.append(this.field2);
      first = false;
    }
    if (isSetField3()) {
      if (!first) sb.append(", ");
      sb.append("field3:");
      sb.append(this.field3);
      first = false;
    }
    if (isSetField4()) {
      if (!first) sb.append(", ");
      sb.append("field4:");
      sb.append(this.field4);
      first = false;
    }
    if (isSetField5()) {
      if (!first) sb.append(", ");
      sb.append("field5:");
      sb.append(this.field5);
      first = false;
    }
    if (isSetField6()) {
      if (!first) sb.append(", ");
      sb.append("field6:");
      sb.append(this.field6);
      first = false;
    }
    if (isSetField7()) {
      if (!first) sb.append(", ");
      sb.append("field7:");
      sb.append(this.field7);
      first = false;
    }
    if (isSetField8()) {
      if (!first) sb.append(", ");
      sb.append("field8:");
      sb.append(this.field8);
      first = false;
    }
    if (isSetField9()) {
      if (!first) sb.append(", ");
      sb.append("field9:");
      sb.append(this.field9);
      first = false;
    }
    if (isSetField10()) {
      if (!first) sb.append(", ");
      sb.append("field10:");
      sb.append(this.field10);
      first = false;
    }
    if (isSetField11()) {
      if (!first) sb.append(", ");
      sb.append("field11:");
      sb.append(this.field11);
      first = false;
    }
    if (isSetField12()) {
      if (!first) sb.append(", ");
      sb.append("field12:");
      sb.append(this.field12);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TupleProtocolTestStructStandardSchemeFactory implements SchemeFactory {
    public TupleProtocolTestStructStandardScheme getScheme() {
      return new TupleProtocolTestStructStandardScheme();
    }
  }

  private static class TupleProtocolTestStructStandardScheme extends StandardScheme<TupleProtocolTestStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TupleProtocolTestStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case -1: // FIELD1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field1 = iprot.readI32();
              struct.setField1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -2: // FIELD2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field2 = iprot.readI32();
              struct.setField2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -3: // FIELD3
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field3 = iprot.readI32();
              struct.setField3IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -4: // FIELD4
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field4 = iprot.readI32();
              struct.setField4IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -5: // FIELD5
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field5 = iprot.readI32();
              struct.setField5IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -6: // FIELD6
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field6 = iprot.readI32();
              struct.setField6IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -7: // FIELD7
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field7 = iprot.readI32();
              struct.setField7IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -8: // FIELD8
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field8 = iprot.readI32();
              struct.setField8IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -9: // FIELD9
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field9 = iprot.readI32();
              struct.setField9IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -10: // FIELD10
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field10 = iprot.readI32();
              struct.setField10IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -11: // FIELD11
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field11 = iprot.readI32();
              struct.setField11IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case -12: // FIELD12
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.field12 = iprot.readI32();
              struct.setField12IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TupleProtocolTestStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetField12()) {
        oprot.writeFieldBegin(FIELD12_FIELD_DESC);
        oprot.writeI32(struct.field12);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField11()) {
        oprot.writeFieldBegin(FIELD11_FIELD_DESC);
        oprot.writeI32(struct.field11);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField10()) {
        oprot.writeFieldBegin(FIELD10_FIELD_DESC);
        oprot.writeI32(struct.field10);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField9()) {
        oprot.writeFieldBegin(FIELD9_FIELD_DESC);
        oprot.writeI32(struct.field9);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField8()) {
        oprot.writeFieldBegin(FIELD8_FIELD_DESC);
        oprot.writeI32(struct.field8);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField7()) {
        oprot.writeFieldBegin(FIELD7_FIELD_DESC);
        oprot.writeI32(struct.field7);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField6()) {
        oprot.writeFieldBegin(FIELD6_FIELD_DESC);
        oprot.writeI32(struct.field6);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField5()) {
        oprot.writeFieldBegin(FIELD5_FIELD_DESC);
        oprot.writeI32(struct.field5);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField4()) {
        oprot.writeFieldBegin(FIELD4_FIELD_DESC);
        oprot.writeI32(struct.field4);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField3()) {
        oprot.writeFieldBegin(FIELD3_FIELD_DESC);
        oprot.writeI32(struct.field3);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField2()) {
        oprot.writeFieldBegin(FIELD2_FIELD_DESC);
        oprot.writeI32(struct.field2);
        oprot.writeFieldEnd();
      }
      if (struct.isSetField1()) {
        oprot.writeFieldBegin(FIELD1_FIELD_DESC);
        oprot.writeI32(struct.field1);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TupleProtocolTestStructTupleSchemeFactory implements SchemeFactory {
    public TupleProtocolTestStructTupleScheme getScheme() {
      return new TupleProtocolTestStructTupleScheme();
    }
  }

  private static class TupleProtocolTestStructTupleScheme extends TupleScheme<TupleProtocolTestStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TupleProtocolTestStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetField1()) {
        optionals.set(0);
      }
      if (struct.isSetField2()) {
        optionals.set(1);
      }
      if (struct.isSetField3()) {
        optionals.set(2);
      }
      if (struct.isSetField4()) {
        optionals.set(3);
      }
      if (struct.isSetField5()) {
        optionals.set(4);
      }
      if (struct.isSetField6()) {
        optionals.set(5);
      }
      if (struct.isSetField7()) {
        optionals.set(6);
      }
      if (struct.isSetField8()) {
        optionals.set(7);
      }
      if (struct.isSetField9()) {
        optionals.set(8);
      }
      if (struct.isSetField10()) {
        optionals.set(9);
      }
      if (struct.isSetField11()) {
        optionals.set(10);
      }
      if (struct.isSetField12()) {
        optionals.set(11);
      }
      oprot.writeBitSet(optionals, 12);
      if (struct.isSetField1()) {
        oprot.writeI32(struct.field1);
      }
      if (struct.isSetField2()) {
        oprot.writeI32(struct.field2);
      }
      if (struct.isSetField3()) {
        oprot.writeI32(struct.field3);
      }
      if (struct.isSetField4()) {
        oprot.writeI32(struct.field4);
      }
      if (struct.isSetField5()) {
        oprot.writeI32(struct.field5);
      }
      if (struct.isSetField6()) {
        oprot.writeI32(struct.field6);
      }
      if (struct.isSetField7()) {
        oprot.writeI32(struct.field7);
      }
      if (struct.isSetField8()) {
        oprot.writeI32(struct.field8);
      }
      if (struct.isSetField9()) {
        oprot.writeI32(struct.field9);
      }
      if (struct.isSetField10()) {
        oprot.writeI32(struct.field10);
      }
      if (struct.isSetField11()) {
        oprot.writeI32(struct.field11);
      }
      if (struct.isSetField12()) {
        oprot.writeI32(struct.field12);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TupleProtocolTestStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(12);
      if (incoming.get(0)) {
        struct.field1 = iprot.readI32();
        struct.setField1IsSet(true);
      }
      if (incoming.get(1)) {
        struct.field2 = iprot.readI32();
        struct.setField2IsSet(true);
      }
      if (incoming.get(2)) {
        struct.field3 = iprot.readI32();
        struct.setField3IsSet(true);
      }
      if (incoming.get(3)) {
        struct.field4 = iprot.readI32();
        struct.setField4IsSet(true);
      }
      if (incoming.get(4)) {
        struct.field5 = iprot.readI32();
        struct.setField5IsSet(true);
      }
      if (incoming.get(5)) {
        struct.field6 = iprot.readI32();
        struct.setField6IsSet(true);
      }
      if (incoming.get(6)) {
        struct.field7 = iprot.readI32();
        struct.setField7IsSet(true);
      }
      if (incoming.get(7)) {
        struct.field8 = iprot.readI32();
        struct.setField8IsSet(true);
      }
      if (incoming.get(8)) {
        struct.field9 = iprot.readI32();
        struct.setField9IsSet(true);
      }
      if (incoming.get(9)) {
        struct.field10 = iprot.readI32();
        struct.setField10IsSet(true);
      }
      if (incoming.get(10)) {
        struct.field11 = iprot.readI32();
        struct.setField11IsSet(true);
      }
      if (incoming.get(11)) {
        struct.field12 = iprot.readI32();
        struct.setField12IsSet(true);
      }
    }
  }

  private static <S extends IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

